logging:
  config: classpath:log4j2.xml
server:
  port: 18080
spring:
  application: 
    name: ume-could-gateway
  cloud: 
    gateway:
      routes:
      - id: defaultRoute
        uri: http://localhost:8081
        predicates:
        - Path=/hp/ume-quickstart-cloud/**
        filters:
        - StripPrefix=2
      - id: defaultRoute
        uri: lb://UME-QUICKSTART-CLOUD
        predicates:
        - Path=/lb/ume-quickstart-cloud/**
        filters:
        - StripPrefix=2

eureka:
  instance:
    lease-expiration-duration-in-seconds: 15
    lease-renewal-interval-in-seconds: 5
  client:
    registryFetchIntervalSeconds: 5
    service-url.defaultZone: http://admin:password@localhost:18089/eureka/

#management:
#  server:
#    port: 18084
#  endpoints:
#    web:
#      base-path: /actuator
#      exposure:
#        include: \*
#        exclude: env,beans
#    health:
#      show-details: always
#  security: 
#    enabled: false
#endpoints:
#  shutdown:
#    enabled: true

